name: murre
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.0
  - pip=23.2.1
  - python=3.10.13
  - torchvision=0.15.2
  - pip:
    - torch==2.0.1
    - open3d==0.18.0
    - opencv-python==4.8.0.76
    - pycolmap==0.0.1
    - tqdm==4.66.1
    - trimesh==4.0.2